/**
 * AIAnalysisService.js
 * Simulates AI analysis for design submissions.
 * Generates mock data for Heatmap, Attention Analysis, Color Harmony, and Scoring.
 */

export const analyzeSubmission = async (submissionData) => {
    return new Promise((resolve) => {
        // Simulate processing time (2-4 seconds)
        const processingTime = Math.floor(Math.random() * 2000) + 2000;

        setTimeout(() => {
            const score = (Math.random() * (9.8 - 7.5) + 7.5).toFixed(1); // Random score between 7.5 and 9.8

            // Mock Data Generation
            const result = {
                score: score,
                summary: generateSummary(score),
                heatmapData: generateHeatmapPoints(),
                focusOrder: generateFocusOrder(),
                colorAnalysis: generateColorAnalysis(),
                designElements: generateDesignElementAnalysis(),
                feedback: generateFeedback(score)
            };

            resolve(result);
        }, processingTime);
    });
};

const generateSummary = (score) => {
    if (score >= 9) return "Mükemmel bir çalışma! Tasarım kurallarına büyük ölçüde sadık kalınmış.";
    if (score >= 8) return "Çok başarılı! Ufak iyileştirmelerle harika olabilir.";
    return "Güzel bir başlangıç. Bazı temel prensipler üzerinde durulabilir.";
};

const generateHeatmapPoints = () => {
    // Generate random heatmap points (x, y, intensity)
    // In a real app, this would be generated by a CNN model processing the image
    const points = [];
    for (let i = 0; i < 5; i++) {
        points.push({
            x: Math.random() * 80 + 10, // 10% to 90%
            y: Math.random() * 80 + 10,
            value: Math.random() * 0.5 + 0.5 // High intensity
        });
    }
    return points;
};

const generateFocusOrder = () => {
    return [
        { id: 1, name: "Main Headline / Hero", score: 95 },
        { id: 2, name: "Call to Action (CTA)", score: 88 },
        { id: 3, name: "Navigation Bar", score: 72 },
        { id: 4, name: "Content Images", score: 65 }
    ];
};

const generateColorAnalysis = () => {
    return {
        harmony: "Analogous",
        primary: "#3B82F6",
        secondary: "#10B981",
        accent: "#F59E0B",
        contrastScore: "AAA (Excellent)"
    };
};

const generateDesignElementAnalysis = () => {
    return [
        { name: "Whitespace", status: "Optimal", score: 9.0 },
        { name: "Typography", status: "Good", score: 8.5 },
        { name: "Consistency", status: "Excellent", score: 9.2 },
        { name: "Alignment", status: "Good", score: 8.8 }
    ];
};

const generateFeedback = (score) => {
    const feedbacks = [
        "CTA butonu konumlandırması 'F-Pattern' okuma düzenine uygun.",
        "Renk kontrastı erişilebilirlik standartlarını karşılıyor.",
        "Tipografi hiyerarşisi kullanıcıyı doğru yönlendiriyor.",
        "Görsel yoğunluğu dengeli, bilişsel yük (cognitive load) ideal seviyede."
    ];

    // Return random 2 feedbacks
    return feedbacks.sort(() => 0.5 - Math.random()).slice(0, 2);
};
